config:
  detect:
    subject:
      # graph & label-files must be fetched and stored on the local machine.
      # You probably want to define these in like-a-look-environment.yaml
      # A Tensorflow pre-trained model can be downloaded at
      # https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz
      inception3:
        graph: '/<localpath>/models/v3.0/tensorflow_inception_graph.pb'
        labels: '/<localpath>/models/v3.0/imagenet_comp_graph_label_strings.txt'

  # The DANER project is highly specific for the Royal Danish Library
  daner:
    # The datadump from "Billedsamlingen", generated for the DANER project.
    # This will be available under http://loar.kb.dk at some point
    # The 'daner_metadata.csv' is a sample from the datadump provided as a resource in the project
    csv: 'daner_metadata.csv'
    resource:
      # In a production setup this should be prefixed with 'https://<the_server>'
      urlprefix: '/like-a-look/resource/'
  resources:
    # Roots are on the local file system. Only files directly under the roots are delivered when
    # a resource is requested.
    roots:
      # These is used by the DANER project and needs to be defined in order to show images from the result.
      #- name: 'faces'
      #  path: '<localpath>/faces/'
      #- name: 'faces_close_cut'
      #  path: '<localpath>/faces_close_cut/'
