openapi: 3.0.2
info:
  version: "${project.version}"
  title: "${project.name}"
  description: |
    Experimental service for finding similar images in collections.
  license:
    name: "${license.name}"
    url: "${license.url}"
servers:
  #  /api must match servlet-mapping in web.xml
  - url: "/${project.artifactId}/api"
    description: "Current server"
paths:

  # https://swagger.io/docs/specification/describing-request-body/file-upload/
  /similar:
    post:
      tags:
        - "${project.name}"
      summary: 'Request images similar to the uploaded image'
      operationId: findSimilarWhole
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  description: 'The image to use as source for the similarity search'
                  type: string
                  format: binary
                collection:
                  description: 'The collection to search for similar images.
                                If none is specified, the default collection will be used'
                  type: string
                sourceID:
                  description: 'Optional ID for the image, used for tracking & debugging'
                  type: string
                maxMatches:
                  description: 'The maximum number of similar images to return'
                  type: integer
                  default: 10

      responses:
        '200':
          description: 'An array of metadata for similar images, including URLs for the images'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WholeImage'

  /collections:
    get:
      tags:
        - "${project.name}"
      summary: 'List the available collections'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /detect/faces:
    post:
      tags:
        - "${project.name}"
      summary: 'Detect human faces in the uploaded image'
      operationId: detectFaces
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  description: 'The image to use as source for face detection'
                  type: string
                  format: binary
                method:
                  description: 'The method used for face detecton'
                  type: string
                  enum: [HaarCascade]
                  default: HaarCascade
                  example: HaarCascade
                sourceID:
                  description: 'Optional ID for the image, used for tracking & debugging'
                  type: string

      responses:
        '200':
          description: 'An array of boxes for the detected faces'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Box'

  /ping:
    get:
      tags:
        - "${project.name}"
      summary: Ping the server to check if the server is reachable.
      operationId: ping
      x-useGenericResponse: false # If enabled the method will return Response
      x-streamingOutput: false # If enabled the method will return StreamingOutput.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    WholeImage:
      type: object
      required:
        - url
      properties:
        sourceID:
          type: string
          description: 'The ID for the source image, if one was provided by the caller'
        imageID:
          type: string
          description: 'The ID for the similar image'
        distance:
          type: number
          format: double
          description: 'The similarity distance: Lower is better, 0 is identical'
        url:
          type: string
          description: 'The URL for the similar image'

    Box:
      type: object
      required:
        - x
        - y
        - width
        - height
      properties:
        sourceID:
          type: string
          description: 'The ID for the source image, if one was provided by the caller'
        faceID:
          type: integer
          description: 'The ID for the detected face. IDs start at 0 and are incremented by 1 for each found face'
        # TODO: The probability that it is really a face
        x:
          type: integer
          description: 'The x coordinate for the bounding box for the face'
        y:
          type: integer
          description: 'The y coordinate for the boundng box for the face. The top of the image is 0'
        width:
          type: integer
          description: 'The width of the bounding box for the face'
        height:
          type: integer
          description: 'The height of the bounding box for the face'

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
